<?php

namespace shop\repositories;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use shop\entities\User\Role;
use shop\repositories\Interfaces\IRoleRepository;

/**
 * DoctrineRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineRoleRepository implements IRoleRepository
{
    private $em;
    private $entityRepository;

    public function __construct(EntityManager $em, EntityRepository $entityRepository){
        $this->em = $em;
        $this->entityRepository = $entityRepository;
    }

    public function get($id){
        /** @var Role $role */
        if(!$role = $this->entityRepository->find($id)){
            throw new NotFoundException('Role not found.');
        }

        return $role;
    }

    /**
     * @param string $name
     * @return Role
     * @throws NotFoundException
     */
    public function getByName($name){
        $role = $this->entityRepository->findOneBy(['name' => $name]);
        if(is_null($role)){
            throw new NotFoundException('Role not found.');
        }

        /** @var Role $role */
        return $role;
    }

    public function add(Role $role){
        if(!is_null($this->entityRepository->findOneBy(['name' => $role->getName()]))){
            throw new RoleDoubleException();
        }

        $this->em->persist($role);
        $this->em->flush($role);
    }

    public function remove(Role $role){
        $this->em->remove($role);
        $this->em->flush($role);
    }
}
